{% set name = "ood-metrics" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ood_metrics-{{ version }}.tar.gz
  sha256: efa8b8e33f95cd05931a148572b7b39c8089c4208edc4db8785cc88269e91431

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<3.11
    - numpy ~=1.22
    - matplotlib-base ~=3.0
    - scikit-learn ~=1.0

test:
  imports:
    - ood_metrics
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest --pyargs ood_metrics

about:
  home: https://github.com/tayden/ood-metrics
  summary: Calculate common OOD detection metrics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tayden
