{% set name = "ood-metrics" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ood_metrics-{{ version }}.tar.gz
  sha256: 5ca0ac4dbb9e2b5dfbc7022000f581eabc46466e0722a487caa221628dca6f5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<3.12
    - numpy ~=1.22
    - matplotlib-base ~=3.0
    - scikit-learn ~=1.0

test:
  imports:
    - ood_metrics
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --pyargs ood_metrics

about:
  home: https://github.com/tayden/ood-metrics
  summary: Calculate common OOD detection metrics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tayden
